### ISSUE TITLE
Error doing an npm clean-install

### ISSUE THREAD

**Issue by bressain** [karaggeorge/mac-screen-capture-permissions#11]
I just added this package to an Electron app and I'm getting this error on a mac mini build machine running `npm clean-install`:

```
> mac-screen-capture-permissions@2.0.0 native_build /[...]/node_modules/mac-screen-capture-permissions
> node-gyp rebuild
  CXX(target) Release/obj.target/screencapturepermissions/screen-capture-permissions.o
../screen-capture-permissions.m:12:22: error: implicit declaration of function 'CGPreflightScreenCaptureAccess' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    hasPermissions = CGPreflightScreenCaptureAccess();
                     ^
1 error generated.
make: *** [Release/obj.target/screencapturepermissions/screen-capture-permissions.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/[...]/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/[...]/.nvm/versions/node/v12.16.3/bin/node" "/[...]/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /[...]/node_modules/mac-screen-capture-permissions
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mac-screen-capture-permissions@2.0.0 native_build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mac-screen-capture-permissions@2.0.0 native_build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /[...]/.npm/_cacache/_logs/2021-04-12T22_49_47_446Z-debug.log
```

An `npm install` works fine on a Macbook Pro or Ubuntu terminal so I suspect it's something to do with my build machine. Any help or hints on how to deal with this error would be appreciated.

**Comment by bressain** [comment]
Good news! I discovered two things:

1. I need to read the docs better, most notably the following:
>Building the module from source requires macOS 11+ SDK
2. The above error is what you'll get if you try to `npm install` on OSX 10.x.

I was able to fix my issue by downgrading to version 1.1.0. Once I have an opportunity to update my build machine, I'll update to 2.0.0. As this is resolved for now, I'm going to close this issue.

**Comment by gilles-yvetot** [comment]
I did the same mistake than you @bressain , Github action stills runs on macos 10.15 :(
While it is mentioned in the docs and upgrading solve the issue, my build process did not fail gracefully and went on. Even after the `install` script failed. Was it the same for you?

**Comment by gilles-yvetot** [comment]
@karaggeorge I am wondering if using `execSync` in the [install script](https://github.com/karaggeorge/mac-screen-capture-permissions/blob/master/install.js) instead of `spawn` would be the reason why `npm ci` does not failed when the script fails

**Comment by bressain** [comment]
> I did the same mistake than you @bressain , Github action stills runs on macos 10.15 :( While it is mentioned in the docs and upgrading solve the issue, my build process did not fail gracefully and went on. Even after the `install` script failed. Was it the same for you?

No, my build blew up quite spectacularly but this was on Gitlab.

**Comment by gilles-yvetot** [comment]
@bressain thanks! I am using lerna to trigger `npm ci` in every sub-packages. Maybe that's why :(

**Comment by LOMFM** [comment]
@bressain 
So what is the correct solution? I have tried to install this using the `npm ci`. But got same error.

So I tried to run my working source on development environment by pasting from another mac pc (that is mac desktop).
That was working.

But when I build the source, got same error again. Please help me asap.

**Comment by bressain** [comment]
@LOMFM I ended up dropping this package. I did notice the other day that [Electron might support some of this functionality now](https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos) though I haven't tried it yet.

**Comment by JCMais** [comment]
The Electron API has no way to request the screen permission, only video and microphone.
